config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#home'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def home
    end

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="container">
  <div class="tabs">
    <div class="tabs_item active">
      投稿内容一覧
    </div>
    <div class="tabs_item">
      タイムライン
    </div>
  </div>
  <% @articles.each do |article| %>
    <%= link_to article_path(id: article.id) do %>
        <div class="card">
          <div class="card_image">
            <%= image_tag 'eyecatch1.png' %>
          </div>
          <div class="card_content">
            <div class="card_title">
                <%= article.title%>
            </div>
            <div class="card_heart">
              <%= image_tag 'heart.svg' %>
              <span>23</span>
            </div>
            <div class="card_detail">
              <%= image_tag 'default-avatar.png' %>
              <div>
                <p>cohki0305</p>
                <p>2020/4/16</p>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="show">
    <p class="show_title">タイトル</p>
    <%= @article.title %>
    <p class="show_content">内容</p>
    <%= @article.content %>
    <div class="show_heart">
      <%= image_tag 'heart.svg'%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MywebApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="container clear">
        <div class="header_items">
          <div class="header_left">
            <h2 class="header_title"><%= link_to 'GO_channel', root_path %></h2>
          </div>
          <div class="header_right">
            <ul class="header_list">
              <li class="header_list_item">投稿する</li>
              <%= link_to '投稿内容一覧', articles_path, class: 'header_list_item' %>
              <li class="header_list_item">チャット</li>
            </ul>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>